definitions:
  - name: symfony-test
    git_repo: ~
    directory: symfony-test
    hostname: symfony-test
    startup_command: docker-compose up
    enabled: true
    autostart: true

  - name: bolt-example
    git_repo: ~
    directory: bolt-example
    hostname: bolt
    startup_command: docker-compose up
    enabled: true
    autostart: true
