definitions:
  - name: symfony-test
    git_repo: ~
    directory: symfony-test
    hostname: symfony-test
    startup_command: docker-compose up
    autostart: true
    port_mappings:
      - guest: 43000
        host: 12000

  - name: bolt-example
    git_repo: ~
    directory: bolt-example
    hostname: bolt
    startup_command: docker-compose up
    autostart: false
    port_mappings:
      - guest: 8080
        host: 12001

  - name: phpdocker
    git_repo: https://github.com/phpdocker-io/phpdocker.io.git
    directory: phpdockerio
    hostname: phpdocker
    startup_command: make init start -e CAROOT=~/local_certificates
    autostart: true
    port_mappings:
      - guest: 10000
        host: 12002
