---

- name: Upgrade system
  become: true
  apt:
    update_cache: true
    upgrade: dist

- name: Install docker
  become: true
  apt:
    pkg:
      - docker.io
      - docker-compose

- name: Allow default user access to docker
  become: true
  user:
    name: vagrant
    groups: docker
    append: yes

- name: Install tooling
  become: true
  apt:
    pkg:
      - make
      - supervisor

- name: Remove unneeded packages & services
  become: true
  apt:
    purge: true
    state: absent
    pkg:
      - snapd
