---

- name: System setup
  hosts: all
  tasks:

    - name: Upgrade system
      become: true
      apt:
        update_cache: true
        upgrade: dist

    - name: Install docker
      become: true
      apt:
        pkg:
          - docker.io
          - docker-compose


