---

- name: System setup
  hosts: all
  tasks:
    - name: Upgrade system
      become: true
      apt:
        update_cache: true
        upgrade: dist

    # Workaround for https://bugs.launchpad.net/bugs/1873506
    # Must use vagrant box version 20210415.0.0 or earlier for this to work
    - name: Install virtualbox-guest-dkms
      become: true
      apt:
        pkg:
          - virtualbox-guest-dkms

    - name: Install docker
      become: true
      apt:
        pkg:
          - docker.io
          - docker-compose

    - name: Install tooling
      become: true
      apt:
        pkg:
          - make
          - supervisor

    - name: Allow default user access to docker
      become: true
      user:
        name: vagrant
        groups: docker
        append: yes

    - name: Check that the somefile.conf exists
      stat:
        path: /vagrant/services.yaml
      register: services_file_result

    - name: Set up services, if any given
      when: services_file_result.stat.exists
      block:
        - name: Load service definitions
          include_vars:
            file: ../services.yaml
            name: services

        - name: Checkout apps
          shell: |
            cd /home/vagrant/projects
            if [[ "{{ item.git_repo }}" != "" && ! -d "{{ item.directory }}" ]]; then
              git clone {{ item.git_repo }} {{ item.directory }}
            fi
          args:
            executable: /bin/bash
          with_items: "{{ services.definitions }}"

        - name: Create supervisor log folder
          file:
            path: /home/vagrant/projects/logs
            owner: vagrant
            group: vagrant
            state: directory

        - name: Write supervisor config for services
          become: true
          template:
            src: templates/supervisor_program.conf.j2
            dest: /etc/supervisor/conf.d/{{ item.name }}.conf
          with_items: "{{ services.definitions }}"

        - name: Restart supervisor
          become: true
          systemd:
            name: supervisor
            state: restarted
