---

# This role installs nginx directly on the vm and sets up a number of reverse proxies to each service we serve
# By running nginx directly on the VM instead of using docker we have access to any docker hosted services
# without requiring each service to connect to a network we define
- name: Checking whether the config file exists
  stat:
    path: /vagrant/config.yaml
  register: config_file_result

- name: Set reverse proxies, if any given
  when: config_file_result.stat.exists
  block:
    - name: Install nginx
      become: true
      apt:
        pkg:
          - nginx

    - name: Remove default site
      become: true
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: Load service definitions
      include_vars:
        file: ../config.yaml
        name: config

    - name: Write nginx config ssl redirect
      become: true
      copy:
        src: templates/https_redirect.conf
        dest: /etc/nginx/sites-enabled/https_redirect.conf
        owner: www-data
        group: www-data

    - name: Write nginx config for services
      become: true
      template:
        src: templates/nginx_service.conf.j2
        dest: /etc/nginx/sites-enabled/{{ item.name }}.conf
        owner: www-data
        group: www-data
      with_items: "{{ config.services }}"
      when: item.gateway is defined and item.gateway | default("", true)

    - name: Create certs folder
      become: true
      file:
        path: /home/vagrant/gateway-certs
        owner: www-data
        group: www-data
        state: directory

    # We must copy these certs into the VM directly as, during boot, nginx might come online before the
    # /vagrant mount is ready
    - name: Copy certs into folder
      become: true
      copy:
        src: ../certs/
        dest: /home/vagrant/gateway-certs
        owner: www-data
        group: www-data

    - name: Test nginx config
      become: true
      shell: nginx -t

    - name: Restart nginx
      become: true
      systemd:
        name: nginx
        state: restarted
